---
version: "3"
services:
  pmm-server:
    container_name: pmm-server
    image: perconalab/pmm-server:dev-container
    volumes:
      - "./:/workspace"
      - "./public:/usr/share/grafana/public"
      - "./conf/grafana.local-dev.ini:/usr/share/grafana/conf/defaults.ini"
    ports:
      - 80:80
      - 443:443
    environment:
      - PMM_DEBUG=1
      - PERCONA_PORTAL_URL=https://portal-dev.percona.com
      - PERCONA_TEST_PLATFORM_ADDRESS=https://check-dev.percona.com:443
      - PERCONA_TEST_PLATFORM_PUBLIC_KEY=RWTkF7Snv08FCboTne4djQfN5qbrLfAjb8SY3/wwEP+X5nUrkxCEvUDJ
      - ENABLE_BACKUP_MANAGEMENT=1
      - NODE_ENV=production
      - PERCONA_TEST_DBAAS=1
      - PERCONA_TEST_DBAAS_PMM_CLIENT=perconalab/pmm-client:dev-latest
      - PERCONA_TEST_VERSION_SERVICE_URL=https://check-dev.percona.com/versions/v1
      - ENABLE_DBAAS=1
      - PERCONA_TEST_SAAS_HOST=check-dev.percona.com
      - PERCONA_TEST_CHECKS_PUBLIC_KEY=RWTkF7Snv08FCboTne4djQfN5qbrLfAjb8SY3/wwEP+X5nUrkxCEvUDJ
#    networks:
#      - minikube

  mysql:
    image: percona:5.7.30
    platform: linux/amd64
    container_name: pmm-agent_mysql
    command: >
      --sql-mode="ANSI_QUOTES"
      --performance-schema --innodb_monitor_enable=all
      --slow_query_log --log_slow_rate_limit=1 --log_slow_admin_statements --log_slow_slave_statements --slow_query_log_file=/mysql/slowlogs/slow.log --long_query_time=0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ps
      - MYSQL_USER=pmm-agent
      - MYSQL_PASSWORD=pmm%*&agent-password
      - UMASK=0777  # for slowlog file
    volumes:
      - ./testdata/mysql:/mysql
#networks:
#  minikube:
#    external: true
