include ./apps/Makefile.include
include ./apps/Makefile.root

.PHONY: run-server
run-server: build-go
	supervisorctl stop grafana
	cp $(shell find ./bin -name "grafana-server") /usr/sbin/grafana-server
	supervisorctl start grafana &
	supervisorctl tail -f grafana
