---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: percona-platform/checkout@v2
      - name: Run with Node 12
        uses: percona-platform/setup-node@v2
        with:
          node-version: 12

      - name: Run tests
        run: |
          yarn install --pure-lockfile --no-progress
          yarn run ci:test-frontend

      - name: Print usefull info on failure
        if: ${{ failure() }}
        run: |
          pwd
          git status
          env
