---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: percona-platform/checkout@v2
      - name: Run with Node 12
        uses: percona-platform/setup-node@v2
        with:
          node-version: 12

      - name: Enable node_modules cache
        uses: percona-platform/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --pure-lockfile --no-progress

      - name: Run tests 
        run: yarn run ci:test-percona-frontend

      - name: Print useful info on failure
        if: ${{ failure() }}
        run: |
          pwd
          git status
          env
