---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Use Node 12'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Check out code
        uses: percona-platform/checkout@v2

      - name: Run tests
        run: |
          yarn install --pure-lockfile --no-progress
          yarn run ci:test-frontend

      - name: Print usefull info on failure
        if: ${{ failure() }}
        run: |
          pwd
          git status
          env
