name: Migrate open PRs
# Migrate open PRs from a superseded release branch to the current release branch and notify authors
on:
  # @PERCONA - disable workflow
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@e5b7989c92b55fe3ac6dd006d6de49082ba8c507 # create-github-app-token (github-script/v9)
        with:
          github_app: grafana-pr-automation
      - name: Migrate PRs
        uses: grafana/grafana-github-actions-go/migrate-open-prs@main
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          ownerRepo: ${{ inputs.ownerRepo }}
          from: ${{ inputs.from }}
          to: ${{ inputs.to }}
          binary_release_tag: 'dev'
