name: PR Checks
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
      - edited
  issues:
    types:
      - milestoned
      - demilestoned

concurrency:
  group: pr-checks-${{ github.event.number }}

permissions:
  statuses: write
  checks: write
  actions: write
  contents: read
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    # @PERCONA - add repo check
    if: github.event.pull_request.draft == false && github.repository == 'grafana/grafana'
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run PR Checks
        uses: ./actions/pr-checks
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-checks
