---
name: UI Tests
on:
  pull_request:

jobs:
  test:
    name: Run UI tests
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Checkout Grafana code
        uses: percona-platform/checkout@v2
        with:
          path: ./grafana

      - name: Run with Node 12
        uses: percona-platform/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        working-directory: ./grafana
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: percona-platform/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies for Grafana
        working-directory: ./grafana
        run: yarn install --prefer-offline --frozen-lockfile --no-progress

      - name: Start Environment
        working-directory: ./grafana
        run: make run-local-env

      - name: Checkout UI tests
        uses: percona-platform/checkout@v2
        with:
          token: ${{ secrets.ROBOT_TOKEN }}
          ref: SAAS-554-tests-for-grafana-prs
          repository: percona/pmm-ui-tests
          path: ./pmm-ui-tests

      - name: Install dependencies for UI tests
        working-directory: ./pmm-ui-tests
        run: npm install

      - name: Run UI tests
        working-directory: ./pmm-ui-tests
        run: npx codeceptjs run -c pr.codecept.js --grep '@grafana-pr'
        
      - name: Attaching artifacts
        if: ${{ always() }}
        uses: percona-platform/upload-artifact@v2
        with:
          name: ui-tests-output
          path: ./pmm-ui-tests/tests/output
